name: websocket_home_work
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  freezed_annotation: ^2.4.4
  flutter_bloc: ^9.1.1
  web_socket_channel: ^3.0.3
  hive_flutter: ^1.1.0
  uuid: ^4.5.1
  flutter_svg: ^2.1.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^2.5.8
flutter:
  uses-material-design: true

  assets:
    - assets/